"""Domain layer: data structures, errors and ports. No I/O lives here."""

from .errors import (
    ConfigurationError,
    LLMError,
    MaptaError,
    SandboxError,
    ToolArgumentError,
    ToolUnavailable,
)
from .models import (
    CommandResult,
    Finding,
    JSONObject,
    ModelResponse,
    ScanOutcome,
    ScanStatus,
    ScanTally,
    Severity,
    Target,
    ToolCall,
    ToolResult,
    ToolSpec,
    TranscriptItem,
    UsageRecord,
    UsageSummary,
    UsageValue,
    targets_from_lines,
    utcnow,
)
from .ports import (
    LLMClient,
    Mailbox,
    MailboxFactory,
    Notifier,
    ProgressReporter,
    ReportStore,
    Sandbox,
    SandboxFactory,
)

__all__ = [
    "CommandResult",
    "ConfigurationError",
    "Finding",
    "JSONObject",
    "LLMClient",
    "LLMError",
    "Mailbox",
    "MailboxFactory",
    "MaptaError",
    "ModelResponse",
    "Notifier",
    "ProgressReporter",
    "ReportStore",
    "Sandbox",
    "SandboxError",
    "SandboxFactory",
    "ScanOutcome",
    "ScanStatus",
    "ScanTally",
    "Severity",
    "Target",
    "ToolArgumentError",
    "ToolCall",
    "ToolResult",
    "ToolSpec",
    "ToolUnavailable",
    "TranscriptItem",
    "UsageRecord",
    "UsageSummary",
    "UsageValue",
    "targets_from_lines",
    "utcnow",
]
